name = "DAQCore"
uuid = "7b03aed3-9854-4651-ba28-76b88bef8818"
authors = ["Paulo Jabardo <pjabardo@ipt.br> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
